// Auto-generated by scripts/generate_sdk.py (工单 21 降级方案)
// Source: /openapi.json

export interface Envelope<T> {
  code: number;
  data: T | null;
  msg: string;
}

export class TradexClient {
  constructor(
    public baseUrl: string = 'http://127.0.0.1:8000',
    public headers: Record<string, string> = {},
  ) {}

  /** Ping */
  async ping(): Promise<any> {
    const url = `/api/v1/ping`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Overview */
  async marketOverview(): Promise<any> {
    const url = `/api/v1/market/overview`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Global Quote */
  async marketGlobal(query: { category?: string }): Promise<any> {
    const url = `/api/v1/market/global?${new URLSearchParams({category: query.category}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Limit Up Down */
  async marketLimitUpDown(query: { direction?: string }): Promise<any> {
    const url = `/api/v1/market/limit-up-down?${new URLSearchParams({direction: query.direction}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Dragon Tiger */
  async marketDragonTiger(query: { numDays?: integer }): Promise<any> {
    const url = `/api/v1/market/dragon-tiger?${new URLSearchParams({num_days: query.numDays}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Flow */
  async fundFlow(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/fund/flow?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Northbound */
  async fundNorthbound(): Promise<any> {
    const url = `/api/v1/fund/northbound`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Quote */
  async priceQuote(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/price/quote?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Kline */
  async priceKline(query: { symbol: string; period?: string; startDate?: string; endDate?: string; adjust?: string }): Promise<any> {
    const url = `/api/v1/price/kline?${new URLSearchParams({symbol: query.symbol, period: query.period, start_date: query.startDate, end_date: query.endDate, adjust: query.adjust}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Intraday */
  async priceIntraday(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/price/intraday?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Search */
  async companySearch(query: { keyword: string }): Promise<any> {
    const url = `/api/v1/company/search?${new URLSearchParams({keyword: query.keyword}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Info */
  async companyInfo(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/company/info?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Profile */
  async companyProfile(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/company/profile?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Competitors */
  async companyCompetitors(query: { symbol: string; industry?: string }): Promise<any> {
    const url = `/api/v1/company/competitors?${new URLSearchParams({symbol: query.symbol, industry: query.industry}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Income */
  async financialIncome(query: { symbol: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/income?${new URLSearchParams({symbol: query.symbol, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Balance */
  async financialBalance(query: { symbol: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/balance?${new URLSearchParams({symbol: query.symbol, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Cashflow */
  async financialCashflow(query: { symbol: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/cashflow?${new URLSearchParams({symbol: query.symbol, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Line Item */
  async financialLineItem(query: { symbol: string; item: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/line-item?${new URLSearchParams({symbol: query.symbol, item: query.item, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Indicators */
  async financialIndicators(query: { symbol: string; numPeriods?: integer }): Promise<any> {
    const url = `/api/v1/financial/indicators?${new URLSearchParams({symbol: query.symbol, num_periods: query.numPeriods}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Growth */
  async financialGrowth(query: { symbol: string; numPeriods?: integer }): Promise<any> {
    const url = `/api/v1/financial/growth?${new URLSearchParams({symbol: query.symbol, num_periods: query.numPeriods}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Per Share */
  async financialPerShare(query: { symbol: string; numPeriods?: integer }): Promise<any> {
    const url = `/api/v1/financial/per-share?${new URLSearchParams({symbol: query.symbol, num_periods: query.numPeriods}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Segments */
  async financialSegments(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/financial/segments?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Stock */
  async newsStock(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/news/stock?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Announcements */
  async newsAnnouncements(query: { symbol?: string; numResults?: integer }): Promise<any> {
    const url = `/api/v1/news/announcements?${new URLSearchParams({symbol: query.symbol, num_results: query.numResults}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Search */
  async newsSearch(query: { keyword: string; symbol?: string; numResults?: integer }): Promise<any> {
    const url = `/api/v1/news/search?${new URLSearchParams({keyword: query.keyword, symbol: query.symbol, num_results: query.numResults}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Industries */
  async industryList(): Promise<any> {
    const url = `/api/v1/industry/list`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Stocks */
  async industryStocks(query: { industry: string }): Promise<any> {
    const url = `/api/v1/industry/stocks?${new URLSearchParams({industry: query.industry}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Concepts */
  async industryConcepts(): Promise<any> {
    const url = `/api/v1/industry/concepts`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Fund Flow */
  async industryFundFlow(query: { sectorType?: string; indicator?: string }): Promise<any> {
    const url = `/api/v1/industry/fund-flow?${new URLSearchParams({sector_type: query.sectorType, indicator: query.indicator}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Pe */
  async industryPe(query: { industry: string; startDate?: string; endDate?: string }): Promise<any> {
    const url = `/api/v1/industry/pe?${new URLSearchParams({industry: query.industry, start_date: query.startDate, end_date: query.endDate}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Macd */
  async indicatorMacd(query: { symbol: string; period?: string; fastPeriod?: integer; slowPeriod?: integer; signalPeriod?: integer }): Promise<any> {
    const url = `/api/v1/indicator/macd?${new URLSearchParams({symbol: query.symbol, period: query.period, fast_period: query.fastPeriod, slow_period: query.slowPeriod, signal_period: query.signalPeriod}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Kdj */
  async indicatorKdj(query: { symbol: string; period?: string; kdjPeriod?: integer; kPeriod?: integer; dPeriod?: integer }): Promise<any> {
    const url = `/api/v1/indicator/kdj?${new URLSearchParams({symbol: query.symbol, period: query.period, kdj_period: query.kdjPeriod, k_period: query.kPeriod, d_period: query.dPeriod}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Rsi */
  async indicatorRsi(query: { symbol: string; period?: string; rsiPeriod?: integer }): Promise<any> {
    const url = `/api/v1/indicator/rsi?${new URLSearchParams({symbol: query.symbol, period: query.period, rsi_period: query.rsiPeriod}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Boll */
  async indicatorBoll(query: { symbol: string; period?: string; bollPeriod?: integer; k?: number }): Promise<any> {
    const url = `/api/v1/indicator/boll?${new URLSearchParams({symbol: query.symbol, period: query.period, boll_period: query.bollPeriod, k: query.k}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Stock */
  async diagnosticStock(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/diagnostic/stock?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Market */
  async diagnosticMarket(): Promise<any> {
    const url = `/api/v1/diagnostic/market`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Technical */
  async diagnosticTechnical(query: { symbol: string; lookBackDays?: integer }): Promise<any> {
    const url = `/api/v1/diagnostic/technical?${new URLSearchParams({symbol: query.symbol, look_back_days: query.lookBackDays}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Create Strategy */
  async writeStrategy(body: any): Promise<any> {
    const url = `/api/v1/write/strategy`;
    const r = await fetch(this.baseUrl + url, { method: 'POST', headers: {...this.headers, 'Content-Type': 'application/json'}, body: JSON.stringify(body) });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Strategies */
  async writeStrategyList(): Promise<any> {
    const url = `/api/v1/write/strategy/list`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Get Strategy */
  async writeStrategyBySid(sid: string): Promise<any> {
    const url = `/api/v1/write/strategy/${sid}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Delete Strategy */
  async writeStrategyBySid(sid: string): Promise<any> {
    const url = `/api/v1/write/strategy/${sid}`;
    const r = await fetch(this.baseUrl + url, { method: 'DELETE', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Add To Watchlist */
  async writeWatchlist(body: any): Promise<any> {
    const url = `/api/v1/write/watchlist`;
    const r = await fetch(this.baseUrl + url, { method: 'POST', headers: {...this.headers, 'Content-Type': 'application/json'}, body: JSON.stringify(body) });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Watchlist */
  async writeWatchlistList(): Promise<any> {
    const url = `/api/v1/write/watchlist/list`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Remove From Watchlist */
  async writeWatchlistBySymbol(symbol: string): Promise<any> {
    const url = `/api/v1/write/watchlist/${symbol}`;
    const r = await fetch(this.baseUrl + url, { method: 'DELETE', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Metrics Json */
  async metricsJson(): Promise<any> {
    const url = `/api/v1/metrics/json`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Slow Queries */
  async metricsSlowQueries(query: { limit?: integer }): Promise<any> {
    const url = `/api/v1/metrics/slow-queries?${new URLSearchParams({limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Access Log */
  async accessLog(query: { limit?: integer; path?: string }): Promise<any> {
    const url = `/api/v1/access-log?${new URLSearchParams({limit: query.limit, path: query.path}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Earnings Forecast */
  async eventEarningsForecast(query: { symbol: string; reportDate?: string; limit?: integer }): Promise<any> {
    const url = `/api/v1/event/earnings-forecast?${new URLSearchParams({symbol: query.symbol, report_date: query.reportDate, limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Institution Survey */
  async eventInstitutionSurvey(query: { symbol: string; startDate?: string; endDate?: string; limit?: integer }): Promise<any> {
    const url = `/api/v1/event/institution-survey?${new URLSearchParams({symbol: query.symbol, start_date: query.startDate, end_date: query.endDate, limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Holder Trades */
  async eventHolderTrades(query: { symbol: string; direction?: string; startDate?: string; endDate?: string; limit?: integer }): Promise<any> {
    const url = `/api/v1/event/holder-trades?${new URLSearchParams({symbol: query.symbol, direction: query.direction, start_date: query.startDate, end_date: query.endDate, limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Share Buyback */
  async eventShareBuyback(query: { symbol: string; progress?: string; limit?: integer }): Promise<any> {
    const url = `/api/v1/event/share-buyback?${new URLSearchParams({symbol: query.symbol, progress: query.progress, limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Equity Pledge */
  async eventEquityPledge(query: { symbol: string; date?: string; limit?: integer }): Promise<any> {
    const url = `/api/v1/event/equity-pledge?${new URLSearchParams({symbol: query.symbol, date: query.date, limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Ipo Calendar */
  async eventIpoCalendar(query: { daysAhead?: integer; limit?: integer }): Promise<any> {
    const url = `/api/v1/event/ipo-calendar?${new URLSearchParams({days_ahead: query.daysAhead, limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Pmi */
  async macroPmi(): Promise<any> {
    const url = `/api/v1/macro/pmi`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Bond Yield Curve */
  async macroBondYieldCurve(query: { curve?: string }): Promise<any> {
    const url = `/api/v1/macro/bond-yield-curve?${new URLSearchParams({curve: query.curve}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Sw Industry History */
  async macroSwIndustryHistory(query: { forceRefresh?: boolean }): Promise<any> {
    const url = `/api/v1/macro/sw-industry-history?${new URLSearchParams({force_refresh: query.forceRefresh}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Sw Industry As Of */
  async macroSwIndustryAsOf(query: { symbol: string; date?: string }): Promise<any> {
    const url = `/api/v1/macro/sw-industry-as-of?${new URLSearchParams({symbol: query.symbol, date: query.date}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Get News */
  async industryNewsGet(query: { track?: string; days?: integer; perSource?: integer }): Promise<any> {
    const url = `/api/v1/industry-news/get?${new URLSearchParams({track: query.track, days: query.days, per_source: query.perSource}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Tracks */
  async industryNewsTracks(): Promise<any> {
    const url = `/api/v1/industry-news/tracks`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

}