// Auto-generated by scripts/generate_sdk.py (工单 21 降级方案)
// Source: /openapi.json

export interface Envelope<T> {
  code: number;
  data: T | null;
  msg: string;
}

export class TradexClient {
  constructor(
    public baseUrl: string = 'http://127.0.0.1:8000',
    public headers: Record<string, string> = {},
  ) {}

  /** Ping */
  async ping(): Promise<any> {
    const url = `/api/v1/ping`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Overview */
  async overview(): Promise<any> {
    const url = `/api/v1/market/overview`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Global Quote */
  async globalQuote(query: { category?: string }): Promise<any> {
    const url = `/api/v1/market/global?${new URLSearchParams({category: query.category}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Limit Up Down */
  async limitUpDown(query: { direction?: string }): Promise<any> {
    const url = `/api/v1/market/limit-up-down?${new URLSearchParams({direction: query.direction}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Dragon Tiger */
  async dragonTiger(query: { numDays?: integer }): Promise<any> {
    const url = `/api/v1/market/dragon-tiger?${new URLSearchParams({num_days: query.numDays}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Flow */
  async flow(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/fund/flow?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Northbound */
  async northbound(): Promise<any> {
    const url = `/api/v1/fund/northbound`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Quote */
  async quote(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/price/quote?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Kline */
  async kline(query: { symbol: string; period?: string; startDate?: string; endDate?: string; adjust?: string }): Promise<any> {
    const url = `/api/v1/price/kline?${new URLSearchParams({symbol: query.symbol, period: query.period, start_date: query.startDate, end_date: query.endDate, adjust: query.adjust}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Intraday */
  async intraday(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/price/intraday?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Search */
  async search(query: { keyword: string }): Promise<any> {
    const url = `/api/v1/company/search?${new URLSearchParams({keyword: query.keyword}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Info */
  async info(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/company/info?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Profile */
  async profile(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/company/profile?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Competitors */
  async competitors(query: { symbol: string; industry?: string }): Promise<any> {
    const url = `/api/v1/company/competitors?${new URLSearchParams({symbol: query.symbol, industry: query.industry}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Income */
  async income(query: { symbol: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/income?${new URLSearchParams({symbol: query.symbol, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Balance */
  async balance(query: { symbol: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/balance?${new URLSearchParams({symbol: query.symbol, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Cashflow */
  async cashflow(query: { symbol: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/cashflow?${new URLSearchParams({symbol: query.symbol, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Line Item */
  async lineItem(query: { symbol: string; item: string; numQuarters?: integer }): Promise<any> {
    const url = `/api/v1/financial/line-item?${new URLSearchParams({symbol: query.symbol, item: query.item, num_quarters: query.numQuarters}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Indicators */
  async indicators(query: { symbol: string; numPeriods?: integer }): Promise<any> {
    const url = `/api/v1/financial/indicators?${new URLSearchParams({symbol: query.symbol, num_periods: query.numPeriods}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Growth */
  async growth(query: { symbol: string; numPeriods?: integer }): Promise<any> {
    const url = `/api/v1/financial/growth?${new URLSearchParams({symbol: query.symbol, num_periods: query.numPeriods}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Per Share */
  async perShare(query: { symbol: string; numPeriods?: integer }): Promise<any> {
    const url = `/api/v1/financial/per-share?${new URLSearchParams({symbol: query.symbol, num_periods: query.numPeriods}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Segments */
  async segments(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/financial/segments?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Stock */
  async stock(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/news/stock?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Announcements */
  async announcements(query: { symbol?: string; numResults?: integer }): Promise<any> {
    const url = `/api/v1/news/announcements?${new URLSearchParams({symbol: query.symbol, num_results: query.numResults}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Search */
  async search(query: { keyword: string; symbol?: string; numResults?: integer }): Promise<any> {
    const url = `/api/v1/news/search?${new URLSearchParams({keyword: query.keyword, symbol: query.symbol, num_results: query.numResults}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Industries */
  async listIndustries(): Promise<any> {
    const url = `/api/v1/industry/list`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Stocks */
  async stocks(query: { industry: string }): Promise<any> {
    const url = `/api/v1/industry/stocks?${new URLSearchParams({industry: query.industry}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Concepts */
  async concepts(): Promise<any> {
    const url = `/api/v1/industry/concepts`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Fund Flow */
  async fundFlow(query: { sectorType?: string; indicator?: string }): Promise<any> {
    const url = `/api/v1/industry/fund-flow?${new URLSearchParams({sector_type: query.sectorType, indicator: query.indicator}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Pe */
  async pe(query: { industry: string; startDate?: string; endDate?: string }): Promise<any> {
    const url = `/api/v1/industry/pe?${new URLSearchParams({industry: query.industry, start_date: query.startDate, end_date: query.endDate}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Macd */
  async macd(query: { symbol: string; period?: string; fastPeriod?: integer; slowPeriod?: integer; signalPeriod?: integer }): Promise<any> {
    const url = `/api/v1/indicator/macd?${new URLSearchParams({symbol: query.symbol, period: query.period, fast_period: query.fastPeriod, slow_period: query.slowPeriod, signal_period: query.signalPeriod}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Kdj */
  async kdj(query: { symbol: string; period?: string; kdjPeriod?: integer; kPeriod?: integer; dPeriod?: integer }): Promise<any> {
    const url = `/api/v1/indicator/kdj?${new URLSearchParams({symbol: query.symbol, period: query.period, kdj_period: query.kdjPeriod, k_period: query.kPeriod, d_period: query.dPeriod}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Rsi */
  async rsi(query: { symbol: string; period?: string; rsiPeriod?: integer }): Promise<any> {
    const url = `/api/v1/indicator/rsi?${new URLSearchParams({symbol: query.symbol, period: query.period, rsi_period: query.rsiPeriod}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Boll */
  async boll(query: { symbol: string; period?: string; bollPeriod?: integer; k?: number }): Promise<any> {
    const url = `/api/v1/indicator/boll?${new URLSearchParams({symbol: query.symbol, period: query.period, boll_period: query.bollPeriod, k: query.k}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Stock */
  async stock(query: { symbol: string }): Promise<any> {
    const url = `/api/v1/diagnostic/stock?${new URLSearchParams({symbol: query.symbol}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Market */
  async market(): Promise<any> {
    const url = `/api/v1/diagnostic/market`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Technical */
  async technical(query: { symbol: string; lookBackDays?: integer }): Promise<any> {
    const url = `/api/v1/diagnostic/technical?${new URLSearchParams({symbol: query.symbol, look_back_days: query.lookBackDays}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Create Strategy */
  async createStrategy(body: any): Promise<any> {
    const url = `/api/v1/write/strategy`;
    const r = await fetch(this.baseUrl + url, { method: 'POST', headers: {...this.headers, 'Content-Type': 'application/json'}, body: JSON.stringify(body) });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Strategies */
  async listStrategies(): Promise<any> {
    const url = `/api/v1/write/strategy/list`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Get Strategy */
  async getStrategy(sid: string): Promise<any> {
    const url = `/api/v1/write/strategy/${sid}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Delete Strategy */
  async deleteStrategy(sid: string): Promise<any> {
    const url = `/api/v1/write/strategy/${sid}`;
    const r = await fetch(this.baseUrl + url, { method: 'DELETE', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Add To Watchlist */
  async addToWatchlist(body: any): Promise<any> {
    const url = `/api/v1/write/watchlist`;
    const r = await fetch(this.baseUrl + url, { method: 'POST', headers: {...this.headers, 'Content-Type': 'application/json'}, body: JSON.stringify(body) });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** List Watchlist */
  async listWatchlist(): Promise<any> {
    const url = `/api/v1/write/watchlist/list`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Remove From Watchlist */
  async removeFromWatchlist(symbol: string): Promise<any> {
    const url = `/api/v1/write/watchlist/${symbol}`;
    const r = await fetch(this.baseUrl + url, { method: 'DELETE', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Metrics Json */
  async metricsJson(): Promise<any> {
    const url = `/api/v1/metrics/json`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  /** Slow Queries */
  async slowQueries(query: { limit?: integer }): Promise<any> {
    const url = `/api/v1/metrics/slow-queries?${new URLSearchParams({limit: query.limit}).toString()}`;
    const r = await fetch(this.baseUrl + url, { method: 'GET', headers: this.headers });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

}